import Head from "next/head";
import FindBestBus from "../components/home/FindBestBus";
import Header from "../components/home/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Plumbing Turkey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="justify-center h-fit pb-36 bg-slate-500 flex">
        <Header />
      </div>
      <div className="justify-center h-fit bg-gray-300 flex">
        <FindBestBus />
      </div>
    </div>
  );
}
